import "./css/globals.css";
import ViweCanvas from "./components/ViweCanvas";

export const metadata = {
  title: "VENTANA",
  description: "Generated by VENTANA",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <ViweCanvas />
      </body>
    </html>
  );
}
